name: flutter_iconica_analysis
version: 8.0.0
description: Lint rules for Dart and Flutter used internally at Iconica Development BV.
repository: https://github.com/Iconica-Development/flutter_iconica_analysis
issue_tracker: https://github.com/Iconica-Development/flutter_iconica_analysis/issues
homepage: https://github.com/Iconica-Development/flutter_iconica_analysis
documentation: https://github.com/Iconica-Development/flutter_iconica_analysis

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter_lints: ^6.0.0
